# USER CONSTS (can be changed)
COOKIE = "AA45B841AFEC8269D8DDA9AF64AF75AE~000000000000000000000000000000~YAAQzbMUAsgFwR6cAQAAr6tMRB4LY2A9iwSTNaEzTiDcxRC1s9AfUv3mlL8XaOkBbw1dpd9c/XE0XF7MJyQXPCmG6xsy0GdtpobQ03hFHNtdiMo9UXMMKxYsOgrEy7FYhIjAypz1ZRrNlgNKTeiJHxjVB+LvqQ/fJIJ8t3St1sPNcXLgISNB/2zG5/bSFaBdZcrAEkgDbo0T6JBzte0kg7jNh6gc87P0pklOvUzRYDF6bnB8K2Q6igFWVW8fDBtg4SUaocLW/D25ezLUyV6ao+DqD+Xn76KfsJd405SuKWjvO1sk/ugi3ucQiiL+d6i/njX62jasyt5e0AjZXiJWjYI7aTJHyKopRFrnwz0KJlKYTAQwIbDSS2RF2LZcrl3Yt4MMHVfQVBD+5c6fFyP6z/VVcafcu/dB2YQ0jHhwe4VqeJEj4ux7xTx0WeVInOTFz3oFJiCO43JkCIJ3kkuOibX9c9T+"
AUTH_1 = "A879935CDA7DD9EA9709330639827956DDE3CB176F9D15D762E2D9F5D95737F7"
AUTH_2 = "FB0079B45F0C237358D0C81D33615F3E272D185542968441A624CAFA35CA93B6"
FILE_SIZE_LIMIT = 200_000_000
EXTENSIONS = [
    # FOUND
    ".avi",
    ".mp4",
    ".mov",
    ".m4a",
    ".m4v",
    ".wav",
    ".docx",
    ".xlsx",
    ".mp3",
    ".vob",
    ".opus",
    ".xls",
    ".amr",
    ".doc",
    ".wmv",
    ".csv",
    ".3gp",
    ".ts",
    ".db",
    # TRYING
    ".m3u",
    ".mid",
    ".mpp",
    ".key",
    ".aae",
    # ".plugin",
    # ".img",
    # ".iso",
    # ".bak",
    # ".torrent",
    # ".numbers",
    # ".pub",
    # ".asf",
    # ".html",
    # ".json",
    # ".css",
    # ".js",
    # ".app",
    # ".bin",
    # ".bat",
    # ".jar",
    # ".exe",
    # ".cmd",
    # ".txt",
    # ".ppt",
    # ".pptx",
    # ".log",
    # ".zip",
    # ".tar",
    # ".xml",
    # ".swf",
    # ".xlr",
    # ".ods",
    # ".flv",
    # ".amv",
    # ".qt",
    # ".ogg",
    # ".drc",
    # ".viv",
    # ".f4v",
    # ".webm",
    # ".mkv",
    # ".ogv",
    # ".gifv",
    # ".rm",
    # ".rmvb",
    # ".asf",
    # ".mpg",
    # ".mpeg",
    # ".dat",
    # ".asf",
    # ".ogm",
    # ".m2ts",
    # ".divx",
    # ".f4a",
    # ".m4p",
    # ".f4p",
    # ".aac",
    # ".aiff",
    # ".alac",
    # ".flac",
    # ".mp1",
    # ".mp2",
    # ".wma",
    # ".raw",
    # ".ra",
    # ".vox",
    # ".dss",
]
FILE_THREADS = 3
EXTENSION_THREADS = 10


# SITE CONSTS (should probably not be changed)
SITE_URL = "https://www.justice.gov/epstein"
SEARCH_URL = "https://www.justice.gov/multimedia-search?"
MAX_PAGES = 381  # might change in future?
NORMAL_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.9",
    "Alt-Used": "www.justice.gov",
    "Connection": "keep-alive",
    "Host": "www.justice.gov",
    # "If-Modified-Since": "Fri, 06 Feb 2026 01:20:33 GMT",
    # "If-None-Match": "\"1770340833-gzip\"",
    "Priority": "u=0, i",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?!",
    "TE": "trailers",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0",
}
SEARCH_HEADERS = {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.9",
    "Alt-Used": "www.justice.gov",
    "Connection": "keep-alive",
    "Host": "www.justice.gov",
    "Priority": "u=0",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0",
    "x-queueit-ajaxpageurl": "https%3A%2F%2Fwww.justice.gov%2Fepstein",
}
COOKIES = {
    "ak_bmsc": COOKIE,
    "justiceGovAgeVerified": "true",
    # "authorization_1": AUTH_1,
    # "authorization_2": AUTH_2,
}

R = "\033[31m"
Y = "\033[33m"
G = "\033[32m"
X = "\033[0m"
